addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script: doxygen Doxyfile && bash script/publish.sh

notifications:
  email: false